theme: minima
title: She read books as one would breathe, to fill up and live
author: GitHub User
email: marissafriedman@comcast.net
description: > # this means to ignore newlines until "baseurl:"
  The adventures of a librarian who loves reader's advisory!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
